OLHA PARA A CLASSE E VERIFICA SE OS METODOS QUE FAZEM PARTE  DESTA CLASSE ESTÃO DE ACORDO COM O PRINCIPIO DA RESPONSABILIDADE UNICA. 

SE NÃO ESTIVER EXTRAI ESTES MÉTODOS PARA CLASSES QUE VÃO SER ESPECIALIZADAS EM EXECUTAR AQUELA AÇÃO QUE ESTAMOS EXTRAINDO DA CLASSE UNIVERSAL.. A CLASSE PASSA A SER MUITO MAIS COESA.

SOLID =>
S- SINGLE RESPONSABILITY PRINCIPLE 
O- OPEN CLOSED: DIZ QUE AS NOSSAS CLASSES TEM QUE SER ABERTA PARA EXTENSÃO E FECHADAS PARA MODIFICAÇÃO. DIZ QUE TEMOS QUE PERMITIR QUE NOSSO SISTEMA POSSA EVOLUIR MAS SEM ALTERAR DETALHES DE IMPLEMENTAÇÃO DE OUTRAS FUNCIONALIDADES QUE JÁ ESTÃO IMPLEMENTADAS EM NOSSO SISTEMA.
SE TIVER QUE ADD UMA FUNCIONALIDADE E PARA QUE ELA SEJA EFETIVAMENTE ATRIBUÍDA NO SISTEMA ISSO CAUSE UMA MODIFICAÇÃO NO SISTEMA ENTÃO NÃO ESTÁ SEGUINDO O PRINCIPIO OPEN CLOSED.
 



