CODE SMELLS CAPACIDADE DE DETECTAR QUANDO UM CODE ORIENTADO A OBJETO NÃO ESTA ESCRITO DA MELHOR FORMA//
 IDENTIFICAR E MELHORAR A FORMA DE RESOLVER//
  COESÃO: UMA CLASSE É COESA QUANDO ELA FAZ SOMENTE UMA ATIVIDADE BEM DEFINIDA, COESÃO É UM PRINCÍPIO LIGADO A RESPONSABILIDADE ÚNICA, CLASSES DEVEM FAZER SOMENTE UMA ÚNICA ATIVIDADE E FAZÊ-LA BEM. SEGUIR O PRINCIPIO DA COESÃO GARANTE A ORGANIZÇÃO DO CÓDIGO, CADA UM NO SISTEMA FAZ UMA UNICA COISA 

  ACOPLAMENTO: É A CARACTERÍSTICA INERENTE A DEPENDENCIA ENTRE CLASSES//
   QUANDO ESTAMOS FAZENDO UM SISTEMA EM JAVA, EVIDENTEMENTE ESTE SISTEMA VAI TER MAIS DE UMA CLASSE, EM UM SISTEMA BANCÁRIO POR EXEMPLO, VAI TER A CLASSE CONTA CORRENTE, PESSOA, CAIXA ELETRONICO, DINHEIRO, ETC, E TODAS ESTAS CLASSES, DE ALGUMA FORMA, VAI TER RELACIONAMENTO ENTRE ESTAS CLASSES, ENTÃO SE EXISTE RELACIONAMENTO, EXISTE DEPENDENCIA, SE EXISTE DEPENDENCIA, SEMPRE VAI EXISTIR ACOPLAMENTO.
   
    CLASSES DISTINTAS SEMPRE ESTÃO MINIMAMENTE ACOPLADAS.
    
     EXISTE O ACOPLAMENTO FRACO: ONDE HÁ DEPENDENCIA, PORÉM NÃO É UMA DEPENDENCIA QUE EXIGE ALTRAÇÃO NAS DUAS CLASSES, EX: SUPONDO QUE TENHO A CLASSE PRODUTO E CONTA POUPANÇA, E POR ALGUM MOTIVO TEMOS QU FAAZSR UMA MUDANÇA NA CLASSE CONTA POUPANÇA, SE PARA EU CONSEGUIR IMPLEMENTAR ESTA MUDANCA NA CONTA POUPANCA EU PRECISO MUDAR A CLASE PRODUTI? NESTE CASO EXITSE UMA FORTE DDEPENDENCIA ENTRE AS DUAS CLASSES
    O ACOPLAMENTO FORTE EH AO CONTRARIO
     OBJETIVO É DIMINUIR O NIVEL DE ACOPLAMENTO DAS CLASSES, OBETIVO É TER ACOPLAMENTOS FRACOS

UMA FORMA DE DIMINUIR O NÉVEL DE ACOPLAMENTO(SÓ TER OS FRACOS) É OBSERVANDO A COESÃO, ENTÃO SE EU CONSIGO TER UM SISTEMA ALTAMENTE COESO, A PROBABILIDADE DE EU TER UM ACOPLAMETO DORTE, ELA DIMINUIR

















